# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 18:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('art', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Motif',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_motif', models.CharField(max_length=100)),
                ('name_art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='art.Art')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='motif',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motif.Motif'),
        ),
        migrations.AddField(
            model_name='comment',
            name='name_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
