# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 10:48
from __future__ import unicode_literals

from django.db import migrations, models
import utils.fields.custom_imagefields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_art', models.CharField(max_length=100)),
                ('img_art', utils.fields.custom_imagefields.CustomImageField2(default='default_art.jpg', max_length=500, upload_to='')),
                ('name_artist', models.CharField(max_length=100)),
                ('info_art', models.TextField(blank=True)),
                ('text_art', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.CharField(choices=[('collage', '콜라주'), ('drawing', '드로잉'), ('installation', '설치미술'), ('new-media', '뉴미디어'), ('graphic-design', '그래픽디자인'), ('photography', '사진'), ('video-art', '비디오 아트'), ('print-making', '프린팅'), ('sculpture', '조각'), ('others', '기타')], max_length=50)),
                ('art', models.ManyToManyField(related_name='art', to='art.Art')),
            ],
        ),
    ]
