# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_art', models.CharField(max_length=100)),
                ('img_art', models.CharField(max_length=500)),
                ('name_artist', models.CharField(max_length=100)),
                ('info_art', models.TextField(blank=True)),
                ('text_art', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_genre', models.CharField(choices=[('Collage', 'Collage'), ('Drawing', 'Drawing'), ('Installation', 'Installation'), ('New Media', 'New Media'), ('Graphic Design', 'Graphic Design'), ('Photography', 'Photography'), ('Video Art', 'Video Art'), ('Print Making', 'Print Making'), ('Sculpture', 'Sculpture'), ('Others', 'Others')], max_length=50)),
                ('art', models.ManyToManyField(related_name='art', to='art.Art')),
            ],
        ),
    ]
