# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-27 07:59
from __future__ import unicode_literals

from django.db import migrations
import utils.fields.custom_imagefields


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='img_art',
            field=utils.fields.custom_imagefields.CustomImageField2(default='art/default_art.jpg', max_length=500, upload_to=''),
        ),
    ]
