# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-16 14:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('art', '0001_initial'),
        ('motif', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='motif.Comment'),
        ),
    ]
